apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorest
spec:
  selector:
    matchLabels:
      app: rest
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: api
        track: stable
    spec:
      containers:
        - image: paddycontainers.azurecr.io/gorest
          name: gorest  
          tty: true
          command: ["/app/main"]              
          ports:
            - name: http
              containerPort: 80
---
