# https://docs.microsoft.com/azure/devops/pipelines/languages/go
pool:
  vmImage: 'ubuntu-16.04' # Other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  projectName: 'goREST'
  registryLogin: 'paddycontainers'
  registryName: 'paddycontainers'
  registryPassword: 'Rfb1vT9QuW=x2v3Z37jKFYNCg11uoT9Y'
  registryServerName: '$(registryName).azurecr.io'
  imageName: 'gorest'  



steps:

- bash: docker build -f Dockerfile -t $(registryServerName)/$(imageName):$(build.buildId) -t $(registryServerName)/$(imageName):latest $(system.defaultWorkingDirectory)/$(projectName)
  displayName: 'docker build'

  
- bash: docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword)
  displayName: 'docker login'

- bash: |
    docker push $(registryServerName)/$(imageName):$(build.buildId)
    docker push $(registryServerName)/$(imageName):latest
  displayName: 'docker push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))